.TH NOVA 1 "May 2018" "v.01" "Please buy my cryptokitty"
.SH NAME
nova - Calculator that makes floating point arithmetic easier in bash
.SH SYPNOSIS
.B "nova"
[-A] [-S] [-M] [-D] [FILE]


.SH Description
Allows floating point arithmetic to be used in bash in a more faster and efficient way. 




.SH Options




.SH Bugs




.SH Author
KryptoMuncher
brettwy861
Willinspire



.SH See also
.B bc
.B cryptotrade

